### ISSUE TITLE
This error appears when trying to build helm:

### ISSUE THREAD

**Issue by knusbaum** [Masterminds/glide#1004]
```
$ glide --version
glide version 0.13.0-dev
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6fdc82]

goroutine 1 [running]:
github.com/Masterminds/glide/path.StripVendor.func1(0xc420296de0, 0x57, 0x0, 0x0, 0x8f3160, 0xc4205502d0, 0x0, 0x0)
	/builddir/glide-0.13.1/_build-glide-xbps/src/github.com/Masterminds/glide/path/strip.go:28 +0x42
path/filepath.walk(0xc420102cd0, 0x4c, 0x8fa0e0, 0xc4205a8ea0, 0xc420396000, 0x0, 0x0)
	/usr/lib/go/src/path/filepath/path.go:377 +0x20d
path/filepath.walk(0xc4203e3040, 0x45, 0x8fa0e0, 0xc4202b60d0, 0xc420396000, 0x0, 0x0)
	/usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0xc420620c40, 0x38, 0x8fa0e0, 0xc4202b6000, 0xc420396000, 0x0, 0x0)
	/usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0xc420620040, 0x31, 0x8fa0e0, 0xc420578d00, 0xc420396000, 0x0, 0x0)
	/usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0xc42043eae0, 0x26, 0x8fa0e0, 0xc4200a3790, 0xc420396000, 0x0, 0x20)
	/usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42043eae0, 0x26, 0xc420396000, 0xc4200a36c0, 0x0)
	/usr/lib/go/src/path/filepath/path.go:403 +0x106
github.com/Masterminds/glide/path.StripVendor(0x8b035e, 0x3b)
	/builddir/glide-0.13.1/_build-glide-xbps/src/github.com/Masterminds/glide/path/strip.go:22 +0x10a
github.com/Masterminds/glide/action.Install(0xc4201f0500, 0x89bc01)
	/builddir/glide-0.13.1/_build-glide-xbps/src/github.com/Masterminds/glide/action/install.go:62 +0x35b
main.commands.func12(0xc42010cc60, 0x0, 0xc42010cc60)
	/builddir/glide-0.13.1/_build-glide-xbps/src/github.com/Masterminds/glide/glide.go:510 +0x2bf
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.HandleAction(0x811280, 0x8ba958, 0xc42010cc60, 0xc420153200, 0x0)
	/builddir/glide-0.13.1/_build-glide-xbps/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:490 +0xc8
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x899e45, 0x7, 0x8984a0, 0x1, 0x0, 0x0, 0x0, 0x8a58bc, 0x20, 0x0, ...)
	/builddir/glide-0.13.1/_build-glide-xbps/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:210 +0xa36
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200c11e0, 0xc4200a0060, 0x3, 0x3, 0x0, 0x0)
	/builddir/glide-0.13.1/_build-glide-xbps/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:255 +0x6a0
main.main()
	/builddir/glide-0.13.1/_build-glide-xbps/src/github.com/Masterminds/glide/glide.go:104 +0x5a9
make: *** [Makefile:140: bootstrap] Error 2
```

**Comment by deimosfr** [comment]
Hi,

Same exact error, how did you resolved it ?

Thanks

**Comment by knusbaum** [comment]
@deimosfr I didn't, but it appears someone else did. The bug isn't present in the master branch.
