### ISSUE TITLE
Failed to download dependencies - Memory violations

### ISSUE THREAD

**Issue by LirazRom** [Masterminds/glide#1018]
using glide 0.13.1 on macOs
when running glide install -v

Replacing existing vendor dependencies
[INFO]	Removing nested vendor and Godeps/_workspace directories...
[INFO]	Removing: /Users/lirazrom/work/trident/vendor/github.com/coreos/etcd/cmd/vendor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x131f192]

goroutine 1 [running]:
github.com/Masterminds/glide/path.StripVendor.func1(0xc0003fe140, 0x50, 0x0, 0x0, 0x1540360, 0xc00057a3f0, 0x0, 0x0)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/path/strip.go:28 +0x42
path/filepath.walk(0xc00029fa90, 0x45, 0x1547640, 0xc000710410, 0xc000454000, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:378 +0x21f
path/filepath.walk(0xc00028d340, 0x3e, 0x1547640, 0xc000701ee0, 0xc000454000, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
path/filepath.walk(0xc00028cf40, 0x3a, 0x1547640, 0xc00062fd40, 0xc000454000, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
path/filepath.walk(0xc00028ce40, 0x35, 0x1547640, 0xc00062fc70, 0xc000454000, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
path/filepath.walk(0xc0003ea930, 0x2e, 0x1547640, 0xc000264d00, 0xc000454000, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
path/filepath.walk(0xc0000d9170, 0x23, 0x1547640, 0xc000264c30, 0xc000454000, 0x0, 0x20)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
path/filepath.Walk(0xc0000d9170, 0x23, 0xc000454000, 0xc000264b60, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:404 +0x105
github.com/Masterminds/glide/path.StripVendor(0x14d5ddf, 0x3b)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/path/strip.go:22 +0x106
github.com/Masterminds/glide/action.Install(0xc0001c1580, 0x14c1501)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/action/install.go:62 +0x351
main.commands.func12(0xc00021e420, 0x0, 0xc00021e420)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/glide.go:510 +0x2b5
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.HandleAction(0x1438080, 0x14e03f0, 0xc00021e420, 0xc0001d8600, 0x0)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:490 +0xc8
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x14bf842, 0x7, 0x14bde6b, 0x1, 0x0, 0x0, 0x0, 0x14cb14f, 0x20, 0x0, ...)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:210 +0x990
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc00020c000, 0xc0000a0090, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:255 +0x687
main.main()
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/glide.go:104 +0x556

**Comment by seantcanavan** [comment]
I am receiving the same exact error myself. No one else in my company is experiencing this issue so I'm leaning towards the latest macOS update as being the culprit.

I've reproduced the error on both `1.10.4` and `1.11.0` so it doesn't appear to be an issue specific to GoLang but rather with some path / directory traversal issue related to macOS.

@LirazRom what version of macOS are you running? I'm running 10.13.6 (17G2307).

Stackoverflow posting: https://stackoverflow.com/questions/52326548/getting-error-when-downloading-dependencies
