### ISSUE TITLE
Getting "runtime error: invalid memory address or nil pointer dereference" with latest release v0.13.2, but working fine in v0.13.1

### ISSUE THREAD

**Issue by mssachan** [Masterminds/glide#1025]
```
panic: runtime error: invalid memory address or nil pointer dereference
18:39:52 [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x71724f]
18:39:52 
18:39:52 goroutine 1 [running]:
18:39:52 github.com/Masterminds/glide/godep/strip.stripGodepWorkspaceHandler(0xc000168b60, 0xe0, 0x0, 0x0, 0x939e40, 0xc0001ed470, 0x0, 0x0)
18:39:52 	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/godep/strip/strip.go:62 +0x4f
18:39:52 path/filepath.walk(0xc00070a380, 0xd5, 0x940ea0, 0xc000b1b380, 0x8da518, 0x0, 0x0)
18:39:52 	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:378 +0x21f
18:39:52 path/filepath.walk(0xc0007065b0, 0xca, 0x940ea0, 0xc000b1b110, 0x8da518, 0x0, 0x0)
18:39:52 	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
18:39:52 path/filepath.walk(0xc000706000, 0xc3, 0x940ea0, 0xc000b1ad00, 0x8da518, 0x0, 0x0)
18:39:52 	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
18:39:52 path/filepath.walk(0xc000aee780, 0xbe, 0x940ea0, 0xc000b1ac30, 0x8da518, 0x0, 0x0)
18:39:52 	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
18:39:52 path/filepath.walk(0xc0009d8370, 0xaf, 0x940ea0, 0xc0002804e0, 0x8da518, 0x0, 0x0)
18:39:52 	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
18:39:52 path/filepath.walk(0xc0002b7970, 0xa4, 0x940ea0, 0xc0006ce0d0, 0x8da518, 0x0, 0x940ea0)
18:39:52 	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
18:39:52 path/filepath.Walk(0xc0002b7970, 0xa4, 0x8da518, 0xc0006ce000, 0x0)
18:39:52 	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:404 +0x105
18:39:52 github.com/Masterminds/glide/godep/strip.GodepWorkspace(0xc0002b7970, 0xa4, 0xc00041e5c0, 0x0)
18:39:52 	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/godep/strip/strip.go:39 +0x117
18:39:52 github.com/Masterminds/glide/path.StripVendor(0x8d0061, 0x3b)
18:39:52 	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/path/strip.go:52 +0x13a
18:39:52 github.com/Masterminds/glide/action.Install(0xc000250540, 0x8bb401)
18:39:52 	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/action/install.go:62 +0x351
18:39:52 main.commands.func12(0xc00017ac60, 0x0, 0xc00017ac60)
18:39:52 	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:510 +0x2b5
18:39:52 github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.HandleAction(0x832ac0, 0x8da6f0, 0xc00017ac60, 0xc000103800, 0x0)
18:39:52 	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:490 +0xc8
18:39:52 github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x8b9609, 0x7, 0x8b7c0b, 0x1, 0x0, 0x0, 0x0, 0x8c539a, 0x20, 0x0, ...)
18:39:52 	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:210 +0x990
18:39:52 github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc00010d380, 0xc0000f6060, 0x3, 0x3, 0x0, 0x0)
18:39:52 	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:255 +0x687
18:39:52 main.main()
18:39:52 	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:104 +0x556
```

**Comment by MMiller-Hairston** [comment]
I ran into this same issue using `glide up -v`. Switched to `glide install .` and it fixed it.

**Comment by adambkaplan** [comment]
Observed this on Fedora 28, kernel 4.18.16-200.fc28.x86_64
