### ISSUE TITLE
Outdated release

### ISSUE THREAD

**Issue by gdm85** [Masterminds/glide#120]
Your 0.6.1 release (https://github.com/Masterminds/glide/releases/download/0.6.1/glide-linux-amd64.zip) is different than the current 0.6.1 branch.

For example, by using the binary from the zip file I get:
```
[WARN] To use Glide, you must set GO15VENDOREXPERIMENT=1
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/Masterminds/glide/cmd.Gopaths(0x0, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/cmd/util.go:121 +0xba
github.com/Masterminds/glide/cmd.CowardMode(0x7f0dabf886a0, 0xc820112b10, 0xc82014e038, 0x0, 0x0, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/cmd/util.go:68 +0x4b
github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo.(*Router).doCommand(0xc82010da00, 0xc820113140, 0x7f0dabf886a0, 0xc820112b10, 0x0, 0x0, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo/router.go:209 +0x86
github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo.(*Router).runRoute(0xc82010da00, 0x8dcb68, 0x6, 0x7f0dabf886a0, 0xc820112b10, 0x8dcb00, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo/router.go:164 +0x4c9
github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo.(*Router).HandleRequest(0xc82010da00, 0x8dcb68, 0x6, 0x7f0dabf886a0, 0xc820112b10, 0xc8200e9400, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo/router.go:131 +0x2fc
main.setupHandler(0xc8201420f0, 0x8dcb68, 0x6, 0x7f0dabf886a0, 0xc820112b10, 0xc82010da00)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:392 +0x2aa
main.commands.func10(0xc8201420f0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:326 +0x4cf
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x8dcb68, 0x6, 0x8dcb60, 0x2, 0xc820133d60, 0x1, 0x1, 0x956ce0, 0x2a, 0x9be700, ...)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:127 +0x1052
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc8200c9500, 0xc82000a1e0, 0x2, 0x2, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:102 +0x494
```

When `GOPATH` is not defined.

**Comment by mattfarina** [comment]
@gdm85 I believe that issue is now fixed.

The branch we tag from is `master`. In the next couple weeks we'll have a pretty big release with the fix for that included. Have you tried to get the latest from master?

**Comment by gdm85** [comment]
@mattfarina the issue I am reporting is that compiling `0.6.1` gives a different binary than the one on your releases. Normally the binary releases are built from the corresponding **tagged** source.

**Comment by mattfarina** [comment]
@gdm85 I thought I built the 0.6.1 release from the tagged source. I'll need to look into that.
