### ISSUE TITLE
glide get failed with error panic: interface conversion: interface {} is nil, not *cfg.Config

### ISSUE THREAD

**Issue by favadi** [Masterminds/glide#174]
I'm trying to `glide get` new library to a vendored repository and glide fails with error.

```
panic: interface conversion: interface {} is nil, not *cfg.Config

goroutine 1 [running]:
github.com/Masterminds/glide/cmd.VendoredCleanUp(0x7f67cb59b780, 0xc8200f7440, 0xc82015e1f8, 0x0, 0x0, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/cmd/vendored.go:37 +0xbff
github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo.(*Router).doCommand(0xc82013ac80, 0xc8200f7c20, 0x7f67cb59b780, 0xc8200f7440, 0x0, 0x0, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo/router.go:209 +0x86
github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo.(*Router).runRoute(0xc82013ac80, 0x94e740, 0x3, 0x7f67cb59b780, 0xc8200f7440, 0x94e700, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo/router.go:164 +0x4c9
github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo.(*Router).HandleRequest(0xc82013ac80, 0x94e740, 0x3, 0x7f67cb59b780, 0xc8200f7440, 0xc8200e2f00, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/cookoo/router.go:131 +0x2fc
main.setupHandler(0xc820075d40, 0x94e740, 0x3, 0x7f67cb59b780, 0xc8200f7440, 0xc82013ac80)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:515 +0x48c
main.commands.func2(0xc820075d40)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:215 +0x898
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x94e740, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9f0c40, 0x4d, 0xa550a0, ...)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:137 +0x107e
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc820075b00, 0xc82000a300, 0x4, 0x4, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:175 +0xfff
main.main()
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:119 +0x73e
```

I can reproduce it every time with travis script: https://github.com/favadi/glide-get-error/blob/0f450a5fe22bea01fe12ad63c9fd2479efacf970/.travis.yml

The travis build log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/97672152/log.txt

**Comment by favadi** [comment]
So `--update-vendored` is causing the problem here.

In [build 7](https://travis-ci.org/favadi/glide-get-error/builds/97673944), I stop deleting .git directory in '/vendor' but keep go get with `--update-vendored` and it still failed with same error.

In [build 8](https://travis-ci.org/favadi/glide-get-error/builds/97674291), I remove `--update-vendored` and it passed.

**Comment by mattfarina** [comment]
@favadi thanks for all the detail. This is a great bug report. Before I even try to repeat the problem I can trace it right to the code block where the issue is stems from.
