### ISSUE TITLE
glide tree command show exception

### ISSUE THREAD

**Issue by ruiyang2015** [Masterminds/glide#295]
here is the stack trace

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xde453]

goroutine 1 [running]:
panic(0x506a20, 0xc82000e0e0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/Masterminds/glide/dependency.srcDir(0x0, 0x0, 0xc8202dddd0)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/dependency/resolver.go:838 +0x33
github.com/Masterminds/glide/dependency.IsSrcDir(0x0, 0x0, 0x35ff4)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/dependency/resolver.go:834 +0x2b
github.com/Masterminds/glide/tree.walkDeps.func1(0x0, 0x0, 0x0, 0x0, 0x9645e0, 0xc8202dddd0, 0x0, 0x0)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/tree/tree.go:48 +0x92
path/filepath.Walk(0x0, 0x0, 0xc820052528, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/path/filepath/path.go:394 +0xa5
github.com/Masterminds/glide/tree.walkDeps(0xc82016c9c0, 0x0, 0x0, 0xc82046f021, 0x9, 0x0, 0x0, 0x0)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/tree/tree.go:80 +0xc0
github.com/Masterminds/glide/tree.Display(0xc82016c9c0, 0x0, 0x0, 0xc82046f021, 0x9, 0x8, 0x0, 0xc8202ddc20)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/tree/tree.go:19 +0x77
github.com/Masterminds/glide/tree.Display(0xc82016c9c0, 0xc8201a39d0, 0x65, 0xc8201e3a11, 0x24, 0x7, 0x0, 0xc820197da0)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82016c9c0, 0xc8201e06c0, 0x5c, 0xc8201ac0e1, 0x1b, 0x6, 0x0, 0xc8201e2a20)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82016c9c0, 0xc82025e140, 0x44, 0xc820179ad1, 0x24, 0x5, 0x0, 0xc82012f200)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82016c9c0, 0xc820254e60, 0x44, 0xc820197a41, 0x24, 0x4, 0x0, 0xc8201792f0)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82016c9c0, 0xc820280d80, 0x54, 0xc8204a9281, 0x34, 0x3, 0x0, 0xc820197260)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82016c9c0, 0xc8204a8480, 0x40, 0xc8201c6f61, 0x20, 0x2, 0x0, 0xc82024b620)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82016c9c0, 0xc820010144, 0x39, 0xc8201765a0, 0x19, 0x1, 0xc820145d00, 0xc820196390)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/action.Tree(0xc820010144, 0x39, 0xc820131500)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/action/tree.go:32 +0x385
main.commands.func12(0xc820131540)
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/glide.go:514 +0x31
github.com/codegangsta/cli.Command.Run(0x5a6d50, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x647da0, 0x37, 0x0, ...)
	/Users/myuser/Ascend.io/godep/src/github.com/codegangsta/cli/command.go:174 +0x1399
github.com/codegangsta/cli.(*App).Run(0xc820131040, 0xc82000a180, 0x2, 0x2, 0x0, 0x0)
	/Users/myuser/Ascend.io/godep/src/github.com/codegangsta/cli/app.go:187 +0x112b
main.main()
	/Users/myuser/Ascend.io/godep/src/github.com/Masterminds/glide/glide.go:117 +0x644

**Comment by mattfarina** [comment]
What version of Glide are you using, how did you get it (download a binary, `go get`, something else), what OS are you on, and what is your `GOPATH`?

**Comment by ruiyang2015** [comment]
I use go get to install the glide, OS is OSX 10.11.3.
GOPATH is empty, I am using go 1.6, with a vendor directory at the project root.

**Comment by mattfarina** [comment]
@ruiyang2015 In Go you cannot escape the `GOPATH`. Glide does use the the `go` tool for some things. What happens if the `GOPATH` is set and your project is within it?

If that fixes it we need to put a better error message in place.

**Comment by deluan** [comment]
I have the same issue with my project: http://github.com/deluan/gosonic. 
Glide 0.10.0 (homebrew)
Mac OS X 10.11.3
PWD: /Users/deluan/Development/go/src/github.com/deluan/gosonic
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/deluan/Development/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by technosophos** [comment]
@deluan With the same stack trace? Or is it different than the original one?

**Comment by deluan** [comment]
Very similar:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xe3d33]

goroutine 1 [running]:
panic(0x549da0, 0xc8200140f0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/Masterminds/glide/dependency.srcDir(0x0, 0x0, 0xc81ffcd1bd)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/dependency/resolver.go:893 +0x33
github.com/Masterminds/glide/dependency.IsSrcDir(0x0, 0x0, 0xc81ffcd1bd)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/dependency/resolver.go:889 +0x2b
github.com/Masterminds/glide/tree.walkDeps.func1(0x0, 0x0, 0x0, 0x0, 0xe085e0, 0xc82065c840, 0x0, 0x0)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/tree/tree.go:48 +0x92
path/filepath.Walk(0x0, 0x0, 0xc8206fe7f8, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/path/filepath/path.go:394 +0xa5
github.com/Masterminds/glide/tree.walkDeps(0xc820196a90, 0x0, 0x0, 0xc820701ee1, 0x12, 0x0, 0x0, 0x0)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/tree/tree.go:93 +0xc0
github.com/Masterminds/glide/tree.Display(0xc820196a90, 0x0, 0x0, 0xc820701ee1, 0x12, 0x6, 0x0, 0xc82065c6f0)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/tree/tree.go:19 +0x77
github.com/Masterminds/glide/tree.Display(0xc820196a90, 0xc820618a40, 0x3f, 0xc8204cf281, 0x1e, 0x5, 0x0, 0xc8204e6390)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc820196a90, 0xc8205a5770, 0x41, 0xc8206b89c1, 0x20, 0x4, 0x0, 0xc82019f500)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc820196a90, 0xc8206d1ae0, 0x41, 0xc820123e61, 0x20, 0x3, 0x0, 0xc8206937d0)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc820196a90, 0xc8204d7640, 0x39, 0xc8201b8ba1, 0x18, 0x2, 0x0, 0xc82019f170)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc820196a90, 0xc82000e1c4, 0x3a, 0xc8201913e1, 0x19, 0x1, 0xc82017ed00, 0xc82019ecc0)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/action.Tree(0xc82000e1c4, 0x3a, 0xc820194200)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/Masterminds/glide/action/tree.go:32 +0x385
main.commands.func13(0xc820194280)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/glide.go:575 +0x31
github.com/codegangsta/cli.Command.Run(0x5ee5b0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x693ea0, 0x37, 0x0, ...)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/codegangsta/cli/command.go:174 +0x1399
github.com/codegangsta/cli.(*App).Run(0xc820135cc0, 0xc82000a300, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/src/github.com/codegangsta/cli/app.go:187 +0x112b
main.main()
	/private/tmp/glide20160324-23307-1mcrn74/glide-0.10.0/glide.go:117 +0x644
```
