### ISSUE TITLE
Glide 0.9.1 fails with panic in case of force updating repo from one protocol to another

### ISSUE THREAD

**Issue by Barberrrry** [Masterminds/glide#302]
Glide 0.9.1

One of repo in vendor directory was cloned by `git` protocol, because it was specified so in one of dependency package `glide.yaml`. In new version of this package `git` protocol was changed to `https` (acually, `vcs` param was removed and `https` is default) and I switched my `glide.yaml` to this new version. After run `glide up --force` glide failed with panic:

```
[WARN] Replacing bitbucket.org/lazadaweb/fastlz with contents from https://bitbucket.org/lazadaweb/fastlz
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x138228]

goroutine 1 [running]:
github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs.(*GitRepo).Version(0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs/git.go:101 +0x1a8
github.com/Masterminds/glide/repo.VcsUpdate(0xc8204cd720, 0xc8202d1810, 0x4c, 0xc820141300, 0x15, 0x1000000, 0x0, 0x0)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/repo/vcs.go:125 +0x1786
github.com/Masterminds/glide/repo.(*MissingPackageHandler).InVendor(0xc8202f1600, 0xc820464461, 0x1e, 0x0, 0x0)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/repo/installer.go:432 +0x3ad
github.com/Masterminds/glide/dependency.(*Resolver).resolveImports(0xc820120800, 0xc8203df710, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/dependency/resolver.go:458 +0x2204
github.com/Masterminds/glide/dependency.(*Resolver).ResolveAll(0xc820120800, 0xc820522840, 0x18, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/dependency/resolver.go:342 +0x3df
github.com/Masterminds/glide/repo.allPackages(0xc820522840, 0x18, 0x18, 0xc820120800, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/repo/installer.go:293 +0x1d1
github.com/Masterminds/glide/repo.(*Installer).Update(0xc82010d860, 0xc820469cc0, 0x0, 0x0)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/repo/installer.go:180 +0x599
github.com/Masterminds/glide/action.Update(0xc82010d860, 0x53a300)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/action/update.go:42 +0x2c4
main.commands.func11(0xc820115680)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/glide.go:501 +0x28e
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x52bfa8, 0x6, 0x52bfa0, 0x2, 0x0, 0x0, 0x0, 0x585b60, 0x1f, 0x0, ...)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:174 +0x1397
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc820115040, 0xc82000a1e0, 0x3, 0x3, 0x0, 0x0)
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:187 +0x1135
main.main()
        /Users/vpetrov/Workspace/go/src/github.com/Masterminds/glide/glide.go:117 +0x642
```

Without `force` param glide keeps `git` protocol repo, so I run with `force`, because it's necessary to me to switch all repos on `https` protocol.

It seems that problem is in 0.9.1 version, because 0.9.0 works fine.

**Comment by mattfarina** [comment]
Thanks for the report. I can reproduce this.
