### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Icedroid** [Masterminds/glide#344]
I use glide version 0.9.3, when run glide, It output: 
[ERROR] Update failed for github.com/astaxie/beego: exit status 1
panic: runtime error: index out of range

goroutine 48 [running]:
panic(0x90abc0, 0xc820012090)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs.NewHgRepo(0x0, 0x0, 0xc82030ccc0, 0x3f, 0x1, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs/hg.go:42 +0x549
github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs.NewRepo(0x0, 0x0, 0xc82030ccc0, 0x3f, 0x0, 0x0, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs/repo.go:155 +0x25a
github.com/Masterminds/glide/cfg.(*Dependency).GetRepo(0xc820190460, 0xc82030ccc0, 0x3f, 0x0, 0x0, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/cfg/config.go:432 +0x12e
github.com/Masterminds/glide/repo.VcsUpdate(0xc820190460, 0xc82030ccc0, 0x3f, 0xc8201803e0, 0x1f, 0x0, 0xc820180380, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/repo/vcs.go:96 +0x1493
github.com/Masterminds/glide/repo.ConcurrentUpdate.func1(0xc82017a340, 0xc820435510, 0xc820435520, 0xc820435500, 0xc8200194a0, 0xc820019500)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/repo/installer.go:257 +0x23c
created by github.com/Masterminds/glide/repo.ConcurrentUpdate
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/repo/installer.go:274 +0x171

**Comment by mattfarina** [comment]
Can you share your `glide.yaml` file or is this project public? A little more detail would make it easier to figure out the problem.

**Comment by plutov** [comment]
We have same issue, attached our glide.yml:
```package: logpacker
import:
- package: github.com/hpcloud/tail
- package: github.com/Pallinder/go-randomdata
- package: github.com/bluele/slack
- package: github.com/bradfitz/gomemcache
  subpackages:
  - memcache
- package: github.com/c9s/goprocinfo
  subpackages:
  - linux
- package: github.com/fsnotify/fsnotify
- package: github.com/vjeantet/grok
- package: github.com/go-ini/ini
- package: github.com/go-sql-driver/mysql
- package: github.com/gorilla/mux
- package: github.com/influxdata/influxdb
  subpackages:
  - client
- package: github.com/lib/pq
- package: github.com/nu7hatch/gouuid
- package: github.com/sdming/goh
  subpackages:
  - Hbase
- package: github.com/subosito/twilio
- package: github.com/tarantool/go-tarantool
- package: github.com/wblakecaldwell/profiler
- package: gopkg.in/Shopify/sarama.v1
- package: gopkg.in/mgo.v2
  subpackages:
  - bson
- package: gopkg.in/olivere/elastic.v2
- package: gopkg.in/olivere/elastic.v3
```

**Comment by krancour** [comment]
Possibly related to #149.
