### ISSUE TITLE
Crash when checking out a Mercurial (hg) repo on Linux

### ISSUE THREAD

**Issue by orospakr** [Masterminds/glide#465]
Doesn't happen on my OS X box, but does happen inside a docker container (the Glide-enabled golang project itself is mounted into the container with the admittedly kind of nasty `vboxsf` filesystem, if that proves relevant).

```
[INFO]	Fetching updates for github.com/devangel/config.
panic: runtime error: index out of range

goroutine 39 [running]:
panic(0x96b460, 0xc82000e060)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs.NewHgRepo(0xc82021bbf0, 0x21, 0xc8201de870, 0x4b, 0xc82021bb01, 0x0, 0x0)
	/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs/hg.go:43 +0x732
github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs.NewRepo(0xc82021bbf0, 0x21, 0xc8201de870, 0x4b, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/Masterminds/glide/vendor/github.com/Masterminds/vcs/repo.go:163 +0x25a
github.com/Masterminds/glide/cfg.(*Dependency).GetRepo(0xc82018b900, 0xc8201de870, 0x4b, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/Masterminds/glide/cfg/config.go:452 +0x12e
github.com/Masterminds/glide/repo.VcsUpdate(0xc82018b900, 0xc8201de870, 0x4b, 0xc8201730f0, 0xc, 0x0, 0xc82016b720, 0x0, 0x0)
	/go/src/github.com/Masterminds/glide/repo/vcs.go:96 +0x1493
github.com/Masterminds/glide/repo.ConcurrentUpdate.func1(0xc82017ab80, 0xc82022c678, 0xc82022c6a0, 0xc82022c690, 0xc8202139e0, 0xc820213a40)
	/go/src/github.com/Masterminds/glide/repo/installer.go:271 +0x308
created by github.com/Masterminds/glide/repo.ConcurrentUpdate
	/go/src/github.com/Masterminds/glide/repo/installer.go:289 +0x171
```

**Comment by orospakr** [comment]
Also, I installed glide itself from git (https://github.com/Masterminds/glide/commit/c25976f8059b0749f821d4e9c3faf7a205114097), and not one of the builds.

**Comment by orospakr** [comment]
Found a clue:  masterminds/vcs's hg suport, while trying to check out bitbucket.org/pkg/inflect, is running hg paths, which is complaining about perms (probably because of that danged filesystem mount!).  There is a bug here, in that masterminds/vcs isn't properly handling errors from hg.

```
root@be0452be7bd1:/go/src/github.com/joist-engineering/force/vendor/bitbucket.org/pkg/inflect# hg paths
not trusting file /go/src/github.com/joist-engineering/force/vendor/bitbucket.org/pkg/inflect/.hg/hgrc from untrusted user 1000, group staff
```

**Comment by mattfarina** [comment]
If you have access denied I'm not sure how Glide can even operate in your environment.

Do you have any suggestions or an idea for a fix?
