### ISSUE TITLE
Build fails in freeBSD

### ISSUE THREAD

**Issue by sapiens-sapide** [Masterminds/glide#482]
Hello,
I tried to install glide on a freeBSD machine but the installation failed :
freeBSD version : 10.0-RELEASE-p9
go version : 1.6.2_1
Steps: 

* `mkdir -p $GOPATH/src/github.com/Masterminds/glide`
* `cd $GOPATH/src/github.com/Masterminds/glide`
* `git clone https://github.com/Masterminds/glide.git ./`
* `make build`

output : 
```
go build -o glide -ldflags "-X main.version=" glide.go
unexpected fault address 0xc820181800
fatal error: fault
[signal 0xa code=0xc addr=0xc820181800 pc=0xc820181800]

goroutine 5 [running]:
runtime.throw(0x9e4730, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820029d80 sp=0xc820029d68
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:21 +0x1e4 fp=0xc820029dd0 sp=0xc820029d80
created by main.(*builder).do
	/usr/local/go/src/cmd/go/build.go:1320 +0x39e

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc8204c4c7c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc8204c4c70)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
main.(*builder).do(0xc820186a10, 0xc820337450)
	/usr/local/go/src/cmd/go/build.go:1323 +0x3c6
main.runBuild(0xc87bc0, 0xc82006c1b0, 0x1, 0x1)
	/usr/local/go/src/cmd/go/build.go:479 +0x4dc
main.main()
	/usr/local/go/src/cmd/go/main.go:181 +0x783

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 3 [semacquire]:
sync.runtime_Semacquire(0xc820186a54)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820186a50)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
main.(*builder).do.func2(0xc8204c4c70, 0xc820186a10, 0xc8204b10c0)
	/usr/local/go/src/cmd/go/build.go:1311 +0xfc
created by main.(*builder).do
	/usr/local/go/src/cmd/go/build.go:1320 +0x39e

goroutine 4 [semacquire]:
sync.runtime_Semacquire(0xc820186a54)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820186a50)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
main.(*builder).do.func2(0xc8204c4c70, 0xc820186a10, 0xc8204b10c0)
	/usr/local/go/src/cmd/go/build.go:1311 +0xfc
created by main.(*builder).do
	/usr/local/go/src/cmd/go/build.go:1320 +0x39e

goroutine 6 [semacquire]:
sync.runtime_Semacquire(0xc820186a54)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820186a50)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
main.(*builder).do.func2(0xc8204c4c70, 0xc820186a10, 0xc8204b10c0)
	/usr/local/go/src/cmd/go/build.go:1311 +0xfc
created by main.(*builder).do
	/usr/local/go/src/cmd/go/build.go:1320 +0x39e

goroutine 7 [semacquire]:
runtime.gopark(0x0, 0xc820077ee0, 0xc8201c8000, 0x4, 0x20, 0xc8201c8000)
	/usr/local/go/src/runtime/proc.go:262 +0x163
created by main.(*builder).do
	/usr/local/go/src/cmd/go/build.go:1320 +0x39e

goroutine 8 [syscall]:
syscall.Syscall(0xc8203aa000, 0x13, 0x20, 0x5, 0x49dd48, 0xc8204aa0c0, 0xc82015b900)
	/usr/local/go/src/syscall/asm_freebsd_amd64.s:21 +0x5
created by main.(*builder).do
	/usr/local/go/src/cmd/go/build.go:1320 +0x39e

goroutine 9 [select]:
main.(*builder).do.func2(0xc8204c4c70, 0xc820186a10, 0xc8204b10c0)
	/usr/local/go/src/cmd/go/build.go:1304 +0x1cf
created by main.(*builder).do
	/usr/local/go/src/cmd/go/build.go:1320 +0x39e

goroutine 10 [select]:
main.(*builder).do.func2(0xc8204c4c70, 0xc820186a10, 0xc8204b10c0)
	/usr/local/go/src/cmd/go/build.go:1304 +0x1cf
created by main.(*builder).do
	/usr/local/go/src/cmd/go/build.go:1320 +0x39e
*** Error code 2

Stop.
make: stopped in /usr/local/goland/src/github.com/Masterminds/glide
```

**Comment by franciscocpg** [comment]
Hi @sapiens-sapide 
I don't see any glide source code error in your panic stack, so for me It look likes more a `go` bug than a `glide` bug.
Anyway, I had successfully installed with your steps in this environment:
```
FreeBSD  10.2-RELEASE-p18 FreeBSD 10.2-RELEASE-p18
go version go1.6.1 freebsd/amd64
```

**Comment by sapiens-sapide** [comment]
Yes, seems it's a go bug.
I can `go build` but `go install` fails. I posted on github.com/golang/go.

Thanks for your reply.

**Comment by franciscocpg** [comment]
Just for reference
https://github.com/golang/go/issues/16136

**Comment by mattfarina** [comment]
@sapiens-sapide thanks for reporting this and @franciscocpg thanks for pointing this to the right place so quickly.
