### ISSUE TITLE
glide tree panics

### ISSUE THREAD

**Issue by hectorj** [Masterminds/glide#507]
v0.11.0

Running `glide tree` on one of my projects ends in a panic:

```
|	|	|	|	|	|-- appengine/cloudsql   ()
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x533263]

goroutine 1 [running]:
panic(0x96d0a0, 0xc82000e170)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/Masterminds/glide/dependency.srcDir(0x0, 0x0, 0xc81fffadc5)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/dependency/resolver.go:1035 +0x33
github.com/Masterminds/glide/dependency.IsSrcDir(0x0, 0x0, 0xc82047aa78)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/dependency/resolver.go:1031 +0x2b
github.com/Masterminds/glide/tree.walkDeps.func1(0x0, 0x0, 0x0, 0x0, 0x7f160e521658, 0xc8200a4750, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/tree/tree.go:48 +0x95
path/filepath.Walk(0x0, 0x0, 0xc8200a4720, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/path/filepath/path.go:394 +0xa5
github.com/Masterminds/glide/tree.walkDeps(0xc82012b1e0, 0x0, 0x0, 0xc82028fb81, 0x12, 0x0, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/tree/tree.go:93 +0x128
github.com/Masterminds/glide/tree.Display(0xc82012b1e0, 0x0, 0x0, 0xc82028fb81, 0x12, 0x7, 0x0, 0xc8200a45a0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/tree/tree.go:19 +0x77
github.com/Masterminds/glide/tree.Display(0xc82012b1e0, 0xc8200ae540, 0x66, 0xc8202abf21, 0x1e, 0x6, 0x0, 0xc820135ef0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82012b1e0, 0xc8200b2770, 0x62, 0xc8201c2041, 0x1a, 0x5, 0x0, 0xc82019dad0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82012b1e0, 0xc8201bc000, 0x50, 0xc820477cc1, 0x37, 0x4, 0x0, 0xc8201f5830)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82012b1e0, 0xc820498300, 0x51, 0xc8202b9941, 0x38, 0x3, 0x0, 0xc820232930)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82012b1e0, 0xc82031f5e0, 0x4d, 0xc820197641, 0x34, 0x2, 0x0, 0xc8203344e0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/tree.Display(0xc82012b1e0, 0xc8200160f4, 0x40, 0xc8201a6069, 0x27, 0x1, 0xc82018f000, 0xc82019aa20)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/tree/tree.go:40 +0x846
github.com/Masterminds/glide/action.Tree(0xc8200160f4, 0x40, 0xc820198200)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/action/tree.go:32 +0x385
main.commands.func14(0xc820198280)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:619 +0x31
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0xa127d0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaba0e0, 0x37, 0x0, ...)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:179 +0x1399
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc82001b1e0, 0xc82000a5c0, 0x2, 0x2, 0x0, 0x0)
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:196 +0x137c
main.main()
	/Users/mfarina/Code/go/src/github.com/Masterminds/glide/glide.go:122 +0x750
```

**Comment by hectorj** [comment]
I just saw the warning saying the command is deprecated... Closing, feel free to re-open if you think it is worth fixing.

**Comment by edrex** [comment]
I *think* (guessing) [that deprecation notice](https://github.com/Masterminds/glide#glide-rebuild) is meant to apply to `glide rebuild` not `glide tree`. Reopen?
