### ISSUE TITLE
panic when run glide install

### ISSUE THREAD

**Issue by shafreeck** [Masterminds/glide#550]
```
[INFO]  Downloading dependencies. Please wait...
[INFO]  Setting references for remaining imports
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4de449]

goroutine 1 [running]:
panic(0x802200, 0xc4200100b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/Masterminds/glide/vendor/gopkg.in/yaml%2ev2.handleErr(0xc4204bcf38)
        /root/Codes/go/src/github.com/Masterminds/glide/vendor/gopkg.in/yaml.v2/yaml.go:153 +0xe7
panic(0x802200, 0xc4200100b0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/Masterminds/glide/cfg.(*Lockfile).MarshalYAML(0xc4204c3c20, 0x81e9c0, 0xc4204c3c20, 0xc4204bcdb8, 0xc4204c3c01)
        /root/Codes/go/src/github.com/Masterminds/glide/cfg/lock.go:51 +0x129
github.com/Masterminds/glide/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc4200e1600, 0x0, 0x0, 0x81e9c0, 0xc420026420, 0x196)
        /root/Codes/go/src/github.com/Masterminds/glide/vendor/gopkg.in/yaml.v2/encode.go:69 +0xe3
github.com/Masterminds/glide/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc4200e1600, 0x0, 0x0, 0x7caa40, 0xc420026420, 0x16)
        /root/Codes/go/src/github.com/Masterminds/glide/vendor/gopkg.in/yaml.v2/encode.go:98 +0x671
github.com/Masterminds/glide/vendor/gopkg.in/yaml%2ev2.Marshal(0x7caa40, 0xc420026420, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/Codes/go/src/github.com/Masterminds/glide/vendor/gopkg.in/yaml.v2/yaml.go:142 +0x11c
github.com/Masterminds/glide/cfg.(*Lockfile).Marshal(0xc4204c3c20, 0xc4204bcfb0, 0x461cff, 0xc4204bd198, 0x2, 0x2)
        /root/Codes/go/src/github.com/Masterminds/glide/cfg/lock.go:31 +0x68
github.com/Masterminds/glide/cfg.(*Lockfile).WriteFile(0xc4204c3c20, 0xc420429e70, 0xa, 0xc420429e70, 0xa)
        /root/Codes/go/src/github.com/Masterminds/glide/cfg/lock.go:76 +0x2f
github.com/Masterminds/glide/action.Update(0xc42019c500, 0x0)
        /root/Codes/go/src/github.com/Masterminds/glide/action/update.go:109 +0x4f7
github.com/Masterminds/glide/action.Install(0xc42019c500, 0x860000)
        /root/Codes/go/src/github.com/Masterminds/glide/action/install.go:29 +0x642
main.commands.func12(0xc4201b6140)
        /root/Codes/go/src/github.com/Masterminds/glide/glide.go:488 +0x33c
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x8679b8, 0x7, 0x865c6a, 0x1, 0x0, 0x0, 0x0, 0x873545, 0x20, 0x0, ...)
        /root/Codes/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:179 +0xbbe
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200a51e0, 0xc42000c220, 0x2, 0x2, 0x0, 0x0)
        /root/Codes/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:196 +0xc00
main.main()
        /root/Codes/go/src/github.com/Masterminds/glide/glide.go:122 +0x5a0
```

**Comment by timoreimann** [comment]
I experience similar issues, presumably rooted at the same underlying problem:

```
[DEBUG]	Unlocking https-github.com-docker-go-units
[WARN]	github.com/stretchr/testify appears to be a vendored package. Unable to set new version. Consider the '--update-vendored' flag.
[DEBUG]	Unlocking https-github.com-stretchr-testify
[WARN]	gopkg.in/yaml.v2 appears to be a vendored package. Unable to set new version. Consider the '--update-vendored' flag.
[DEBUG]	Unlocking https-gopkg.in-yaml.v2
[DEBUG]	Locking https-github.com-pmezard-go-difflib
[WARN]	github.com/pmezard/go-difflib appears to be a vendored package. Unable to set new version. Consider the '--update-vendored' flag.
[DEBUG]	Unlocking https-github.com-pmezard-go-difflib
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xdec2e]

goroutine 1 [running]:
panic(0x402700, 0xc4200140c0)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
github.com/Masterminds/glide/cfg.Locks.Less(0xc42044b880, 0x3, 0x3, 0x1, 0x0, 0xc42043f820)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/cfg/lock.go:147 +0x7e
github.com/Masterminds/glide/cfg.(*Locks).Less(0xc42043f820, 0x1, 0x0, 0x8)
	<autogenerated>:9 +0x78
sort.insertionSort(0x639420, 0xc42043f820, 0x0, 0x3)
	/usr/local/Cellar/go/1.7/libexec/src/sort/sort.go:25 +0x6e
sort.quickSort(0x639420, 0xc42043f820, 0x0, 0x3, 0x4)
	/usr/local/Cellar/go/1.7/libexec/src/sort/sort.go:207 +0x1eb
sort.Sort(0x639420, 0xc42043f820)
	/usr/local/Cellar/go/1.7/libexec/src/sort/sort.go:222 +0x80
github.com/Masterminds/glide/cfg.NewLockfile(0xc4202b6300, 0x41, 0x60, 0xc420279a80, 0x3, 0x4, 0xc420420cc0, 0x40, 0xc42011e630, 0x4, ...)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/cfg/lock.go:225 +0x47d
github.com/Masterminds/glide/action.Update(0xc4201ab440, 0x10100)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/action/update.go:90 +0x41f
main.commands.func13(0xc4201ae3c0)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/glide.go:606 +0x3d1
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x467f29, 0x6, 0x466886, 0x2, 0x0, 0x0, 0x0, 0x473442, 0x1f, 0x0, ...)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:179 +0xbbe
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200c71e0, 0xc420074050, 0x5, 0x5, 0x0, 0x0)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:196 +0xc00
main.main()
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/glide.go:122 +0x5a0
```

It's at a different section of `lock.go` but apparently also related to the fact that an element of `Locks` (a pointer to `Lock`) is nil.

Tested with the latest master, i.e., commit 3e49dce57f4a3a1e9bc55475065235766000d2f0. Version 0.11.1 does not seem to have this problem.

Happy to share more information if needed.

Thanks!

**Comment by timoreimann** [comment]
git bisect tells me the culprit is commit ee9b54d6057a6f6cdb504bafea0bfde5772931b3.

**Comment by mattfarina** [comment]
Can anyone share a glide yaml and lock file to reproduce this?

**Comment by mattfarina** [comment]
@timoreimann and @shafreeck can you test the PR fix at #557? I think this fixes it.

**Comment by timoreimann** [comment]
@mattfarina sorry for not getting back earlier to you to pass on a glide.yaml/.lock file. I just tried the PR but it still panics:

```
[INFO]	--> Exporting golang.org/x/text
[INFO]	--> Exporting k8s.io/kubernetes
[INFO]	--> Exporting bitbucket.org/ww/goautoneg
[INFO]	--> Exporting gopkg.in/yaml.v2
[INFO]	Replacing existing vendor dependencies
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe5a0d]

goroutine 1 [running]:
panic(0x40b4c0, 0xc4200140c0)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.HandleAction.func1(0xc4207f57d8)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:472 +0x29e
panic(0x40b4c0, 0xc4200140c0)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:458 +0x243
github.com/Masterminds/glide/cfg.Locks.Less(0xc4206e81b0, 0x5, 0x6, 0x1, 0x0, 0xc42024ac80)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/cfg/lock.go:147 +0x3d
github.com/Masterminds/glide/cfg.(*Locks).Less(0xc42024ac80, 0x1, 0x0, 0x8)
	<autogenerated>:9 +0x78
sort.insertionSort(0x6484a0, 0xc42024ac80, 0x0, 0x5)
	/usr/local/Cellar/go/1.7/libexec/src/sort/sort.go:25 +0x6e
sort.quickSort(0x6484a0, 0xc42024ac80, 0x0, 0x5, 0x6)
	/usr/local/Cellar/go/1.7/libexec/src/sort/sort.go:207 +0x1eb
sort.Sort(0x6484a0, 0xc42024ac80)
	/usr/local/Cellar/go/1.7/libexec/src/sort/sort.go:222 +0x80
github.com/Masterminds/glide/cfg.NewLockfile(0xc42027c000, 0x43, 0x60, 0xc4202e1480, 0x3, 0x4, 0xc4201bef00, 0x40, 0xc4201326e0, 0x4, ...)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/cfg/lock.go:225 +0x483
github.com/Masterminds/glide/action.Update(0xc4201bf480, 0x470100)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/action/update.go:74 +0x30b
main.commands.func13(0xc4201d43c0, 0x0, 0x0)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/glide.go:662 +0x3cd
reflect.Value.call(0x3f91e0, 0x4b1cc0, 0x13, 0x470b54, 0x4, 0xc4207f5778, 0x1, 0x1, 0x92738, 0x465b80, ...)
	/usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x3f91e0, 0x4b1cc0, 0x13, 0xc4207f5778, 0x1, 0x1, 0xf8ad, 0x140, 0x140)
	/usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:302 +0xa4
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.HandleAction(0x3f91e0, 0x4b1cc0, 0xc4201d43c0, 0x0, 0x0)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:481 +0x1e0
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x471b83, 0x6, 0x4704c4, 0x2, 0x0, 0x0, 0x0, 0x47d2a4, 0x1f, 0x0, ...)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:186 +0xc26
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc42015c600, 0xc420096000, 0x5, 0x5, 0x0, 0x0)
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:235 +0x60c
main.main()
	/Users/treimann/Development/go/src/github.com/Masterminds/glide/glide.go:122 +0x55c
```

I suppose my glide files would still be helpful to you; will try to publish them shortly.

**Comment by timoreimann** [comment]
@mattfarina I put together an [example repo](https://github.com/timoreimann/glide-demo) that enables to reproduce the issue by running `glide up -v -s`. Please see the [glide.yaml](https://github.com/timoreimann/glide-demo/blob/d157065fdb379e7f7d680e9e324efb954e397022/glide.yaml) file.

Let me know if you need anything more from me. Thanks!

**Comment by mattfarina** [comment]
@timoreimann thanks for the example repo. It helped me to reproduce the problem, understand what was happening (and why my previous change didn't work, fix the problem, and prove it.
