### ISSUE TITLE
panic when internet is out

### ISSUE THREAD

**Issue by abourget** [Masterminds/glide#60]
Using glide `dev`, with Internet disconnected:

```
$ glide pin
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4eeece]

goroutine 1 [running]:
github.com/Masterminds/vcs.detectVcsFromRemote(0xc8201358c0, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/abourget/go/src/github.com/Masterminds/vcs/vcs_remote_lookup.go:104 +0x3fe
github.com/Masterminds/vcs.NewRepo(0xc8201358c0, 0x18, 0xc820015360, 0x46, 0x0, 0x0, 0x0, 0x0)
	/home/abourget/go/src/github.com/Masterminds/vcs/repo.go:108 +0x61
github.com/Masterminds/glide/cmd.(*Dependency).GetRepo(0xc8200acd80, 0xc820015360, 0x46, 0x0, 0x0, 0x0, 0x0)
	/home/abourget/go/src/github.com/Masterminds/glide/cmd/yaml.go:423 +0x12e
github.com/Masterminds/glide/cmd.VcsLastCommit(0xc8200acd80, 0xc82013a6c0, 0x35, 0x0, 0x0, 0x0, 0x0)
	/home/abourget/go/src/github.com/Masterminds/glide/cmd/get_imports.go:288 +0x136
github.com/Masterminds/glide/cmd.UpdateReferences(0x7fb8fca8e690, 0xc820108c90, 0xc820030278, 0x0, 0x0, 0x0, 0x0)
	/home/abourget/go/src/github.com/Masterminds/glide/cmd/update_references.go:20 +0x390
github.com/Masterminds/cookoo.(*Router).doCommand(0xc8200f9be0, 0xc820109650, 0x7fb8fca8e690, 0xc820108c90, 0x0, 0x0, 0x0, 0x0)
	/home/abourget/go/src/github.com/Masterminds/cookoo/router.go:209 +0x86
github.com/Masterminds/cookoo.(*Router).runRoute(0xc8200f9be0, 0x8ceff8, 0x3, 0x7fb8fca8e690, 0xc820108c90, 0x8cef00, 0x0, 0x0)
	/home/abourget/go/src/github.com/Masterminds/cookoo/router.go:164 +0x4c9
github.com/Masterminds/cookoo.(*Router).HandleRequest(0xc8200f9be0, 0x8ceff8, 0x3, 0x7fb8fca8e690, 0xc820108c90, 0xc8200df400, 0x0, 0x0)
	/home/abourget/go/src/github.com/Masterminds/cookoo/router.go:131 +0x2fc
main.setupHandler(0xc8201360f0, 0x8ceff8, 0x3, 0x7fb8fca8e690, 0xc820108c90, 0xc8200f9be0)
	/home/abourget/go/src/github.com/Masterminds/glide/glide.go:335 +0x2aa
main.commands.func7(0xc8201360f0)
	/home/abourget/go/src/github.com/Masterminds/glide/glide.go:238 +0x233
github.com/codegangsta/cli.Command.Run(0x8ceff8, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x966e80, 0x48, 0x9a7340, ...)
	/home/abourget/go/src/github.com/codegangsta/cli/command.go:127 +0x1052
github.com/codegangsta/cli.(*App).Run(0xc8200bd400, 0xc82000a480, 0x2, 0x2, 0x0, 0x0)
	/home/abourget/go/src/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
	/home/abourget/go/src/github.com/Masterminds/glide/glide.go:100 +0x494
```

**Comment by technosophos** [comment]
I think this should be fixed by re-fetching the VCS package. I just pushed a fix.

**Comment by abourget** [comment]
Seems fixed, will reopen if needed.
